name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: Deploy to Cloud Foundry
      uses: jhunt/cf-push@v1
      with:
        api:      ${{secrets.CF_API_HOST}}
        org:      ${{ secrets.CF_ORG }}
        space:    ${{ secrets.CF_SPACE }}
        username: ${{ secrets.CF_USERNAME }}
        password: ${{ secrets.CF_PASSWORD }}
        manifest: manifest.yml
        validate: false
